default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: carbon_grid_development

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: carbon_grid_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: carbon_grid_production